# Generated by Django 2.2.9 on 2020-03-18 11:35

from django.db import migrations, models
import onadata.libs.utils.common_tools


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0061_auto_20200318_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xform',
            name='uuid',
            field=models.CharField(default=onadata.libs.utils.common_tools.get_uuid, max_length=36),
        ),
    ]
